src/main/java/com/education/springstuding/model/Message.java
package com.education.springstuding.model;

import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;

@Entity
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Please fill the message")
    @Length(max = 2048, message = "Message too long (more than 2kB)")
    private String text;
    @Length(max = 255, message = "Message too long (more than 255)")
    private String tag;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User author;

    private String filename;

    public Message() {
    }

    public Message(@NotBlank(message = "Please fill the message") @Length(max = 2048, message = "Message too long (more than 2kB)") String text, @Length(max = 255, message = "Message too long (more than 255)") String tag, User author, String filename) {
        this.text = text;
        this.tag = tag;
        this.author = author;
        this.filename = filename;
    }

    public String getAuthorName(){
        return author != null ? author.getUsername() : "<none>";
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }
}

src/main/java/com/education/springstuding/controller/RegistrationController.java
package com.education.springstuding.controller;

import com.education.springstuding.model.User;
import com.education.springstuding.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;

import javax.validation.Valid;
import java.util.Map;

@Controller
public class RegistrationController {

    @Autowired
    private UserService userService;

    @GetMapping("/registration")
    public String registration(){
        return "registration";
    }

    @PostMapping("/registration")
    public String addUser(
            @Valid User user,
            BindingResult bindingResult,
            Model model
    ){
        if (bindingResult.hasErrors()){
            Map<String, String> errors = ControllerUtil.getErrors(bindingResult);
            model.mergeAttributes(errors);
            return "registration";
        }
        if (!userService.addNewUser(user)){
            model.addAttribute("usernameError", "User exists!");
            return "registration";
        }
        return "redirect:/login";
    }

    @GetMapping("/activate/{code}")
    public String activate(@PathVariable final String code, Model model){
        final Boolean isActivated = userService.activateUser(code);
        if (isActivated) {
            model.addAttribute("message", "User successfully activated");
        } else {
            model.addAttribute("message", "Activation code is not found!");
        }
        return "/login";
    }
}

src/main/resources/templates/home.ftl
<#import "parts/common.ftl" as common>
<@common.page>
<div class="form-row">
    <div class="form-group col-md-6">
        <form method="get" action="/home">
            <input type="text" name="filter" placeholder="Enter tag" value="${filter?if_exists}"/>
            <button type="submit" class="btn btn-primary c">Search</button>
        </form>
    </div>
</div>

<a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1"
   role="button" aria-expanded="false" aria-controls="multiCollapseExample1">
    Add new message
</a>
<div class="collapse multi-collapse <#if message??>show</#if>" id="multiCollapseExample1">
    <form method="post" enctype="multipart/form-data">
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="inputTag" class="m-2 text-info">Tag</label>
                <input type="text" class="form-control ${(tagError??)?string('is-invalid', '')}"
                       name="tag" placeholder="Enter your tag"/>
                <#if tagError??>
                <div class="invalid-feedback">
                    ${tagError}
                </div>
                </#if>
            </div>
            <div class="form-group col-md-3">
                <label for="inputFile" class="m-2 text-info">File</label>
                <div class="custom-file">
                    <input type="file" name="file" id="inputFile"/>
                    <label class="custom-file-label" for="inputFile">Choose file</label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="inputMessage" class="text-info">Message</label>
            <input type="text" class="form-control ${(textError??)?string('is-invalid', '')}"
                   value="<#if message??>${message.text}</#if>" name="text" placeholder="Enter your message"/>
            <#if textError??>
                <div class="invalid-feedback">
                    ${textError}
                </div>
            </#if>
        </div>
        <input type="hidden" name="_csrf" value="${_csrf.token}"/>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Add message</button>
        </div>
    </form>
</div>

<div class="p-1 m-2" align="center">
    <h2>List messages</h2>
</div>

<div class="card-columns border-success mb-3" style="max-width: 108rem;">
    <#list messages as message>
        <div class="card border-info mb-3" style="max-width: 18rem;">
            <div class="card-header">Tag: #${message.tag}</div>
        <#if message.filename??>
        <img width="150" height="150" src="/img/${message.filename}" class="rounded mx-auto d-block">
        </#if>
            <div class="card-body m-2">
                <p class="card-text text-info">${message.text}</p>
            </div>
            <div class="card-footer bg-info text-white">
                Author:  ${message.authorName}
            </div>
        </div>
    <#else>
    No message
    </#list>
</div>
</@common.page>

src/main/resources/templates/index.ftl
<#import "parts/common.ftl" as common>
<@common.page>
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Hello, guest!</h1>
        <p class="lead">This is simple app writen by Spring Boot</p>
    </div>
</div>

</@common.page>

src/main/resources/templates/login.ftl
<#import "parts/common.ftl" as common>
<#import "parts/login.ftl" as login>
<@common.page>
<div class="form-group" align="center">
    <#if Session?? && Session.SPRING_SECURITY_LAST_EXCEPTION??>
    <div class="col-sm-5 alert alert-danger" role="alert">
        ${Session.SPRING_SECURITY_LAST_EXCEPTION.message}
    </div>
    </#if>
    <#if message??>
    <div class="col-sm-5 alert alert-info" role="alert">
        ${message?if_exists}
    </div>
        </#if>
    <@login.login "/login" false/>
<div align="center">
    <a href="/registration" class="btn btn-link">Registration</a>
</div>
</div>
</@common.page>

src/main/resources/templates/profile.ftl
<#import "parts/common.ftl" as common>
<@common.page>
<div class="form-group row" align="center">
    <label for="staticEmail" class="col-sm-6 col-form-label alert alert-success ml-5"><h3>User: ${username}</h3></label>
</div>
    <form method="post">
        <div class="form-group row" for="validation">
            <label for="staticEmail" class="col-sm-2 col-form-label alert alert-primary ml-5">Edit email:</label>
            <div class="col-sm-4">
                <input type="email" name="email" class="form-control" value="${email!''}"
                       placeholder="example@example.com"/>
            </div>
        </div>
        <div class="form-group row" for="validation">
            <label for="staticEmail" class="col-sm-2 col-form-label alert alert-primary ml-5">Edit password:</label>
            <div class="col-sm-4">
                <input type="password"  name="password" class="form-control" placeholder="Password">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label"></label>
            <div class="col-sm-3">
                <input type="hidden" name="_csrf" value="${_csrf.token}" />
                <button type="submit" class="btn btn-success btn-block">Save</button>
                <a href="/home" class="btn btn-danger btn-block">Cancel</a>
            </div>
        </div>
    </form>
</@common.page>

src/main/resources/templates/registration.ftl
<#import "parts/common.ftl" as common>
<#import "parts/login.ftl" as login>
<@common.page>
<div class="col-form-label alert alert-success ml-5" align="center">
    <h2>Add New User</h2>
</div>
<div align="center"><h4>${message?if_exists}</h4></div>
    <@login.login "/registration" true/>
<div align="center">
    <a href="/login" class="btn btn-link">Login Page</a>
</div>
</@common.page>

src/main/resources/templates/userEdit.ftl
<#import "parts/common.ftl" as common>
<@common.page>
<div class="form-group row" align="center">
    <label for="staticEmail" class="col-sm-6 col-form-label alert alert-success ml-5">
        <h3>Edit user by id ${user.id}</h3></label>
</div>
<form action="/user" method="post">
    <div class="form-group row" for="validation">
        <label for="staticEmail" class="col-sm-2 col-form-label alert alert-primary ml-5">Edit user name:</label>
        <div class="col-sm-4">
            <input type="text" name="username" class="form-control" value="${user.username}" >
        </div>
    </div>
    <div class="form-group row" for="validation">
        <label for="staticEmail" class="col-sm-2 col-form-label alert alert-primary ml-5">Edit email:</label>
        <div class="col-sm-4">
            <input type="mail" name="email" class="form-control" value="${user.email}" >
        </div>
    </div>
    <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label alert alert-primary ml-5">Edit user role:</label>
        <div class="col-sm-4">
            <#list roles as role>
                <div>
                    <label><input type="checkbox" name="${role}" ${user.roles?seq_contains(role)?string("checked", "")}>${role}</label>
                </div>
            </#list>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-3">
            <input type="hidden" value="${user.id}" name="userId"/>
            <input type="hidden" name="_csrf" value="${_csrf.token}" />
            <button type="submit" class="btn btn-success btn-block">Save</button>
            <a href="/home" class="btn btn-danger btn-block">Cancel</a>
        </div>
    </div>
</form>
</@common.page>

src/main/resources/templates/userList.ftl
<#import "parts/common.ftl" as common>
<@common.page>
<div class="p-1 m-2" align="center">
   <h2><p class="font-weight-bold">List of user</p></h2>
</div>
<table class="table table-bordered" align="center">
    <thead class="bg-primary text-white" align="center">
    <th scope="col">id user</th>
    <th scope="col">User name</th>
    <th scope="col">User active</th>
    <th scope="col">Email</th>
    <th scope="col">Role</th>
    <th scope="col">Edit</th>
    </thead>
    <tbody>
    <#list users as user>
    <tr scope="row" align="center">
        <td>${user.id}</td>
        <td>${user.username}</td>
        <td>${user.active?then('Yes', 'No')}</td>
        <td>${user.email}</td>
        <td><#list user.roles as role>${role}<#sep>, </#list></td>
        <td><a href="/user/${user.id}">Edit</a> </td>
    </tr>
    </#list>
    </tbody>
</table>
</@common.page>